export const FETCH_CINEMA_SYSTEM_LIST = "FETCH_CINEMA_SYSTEM_LIST"
export const FETCH_THEATERS_LIST = "FETCH_THEATERS_LIST"
export const FETCH_ROOM_LIST = "FETCH_ROOM_LIST"
export const TEST = "TEST"
