export const FETCH_MOVIE_LIST = "FETCH_MOVIE_LIST"
export const EDIT_MOVIE = "EDIT_MOVIE"
export const SET_EDITED = "SET_EDITED"
export const SET_DELETED = "SET_DELETED"
export const SET_DETAIL = "SET_DETAIL"
export const SET_POPUP = "SET_POPUP"